apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: weatherorg
      defaultBucket: weather
      tlsSkipVerify: true
    secureJsonData:
      token: mytoken123456789
    editable: true
